### ISSUE TITLE
Create input files (two) for the case and control

### ISSUE THREAD

**Issue by mahdi-b** [mahdi-b/GWASDS#3]
Matrix with individuals as rows and columns and SNPs.
Naturally, the order of columns should be the same across the two files.

**Comment by mahdi-b** [comment]
Generating the files is not optimal due to the file size. Instead, we will write a script that generates DataFrames on the fly. The simulation will use a seed to avoid creating new "different" data each time the script is run.

**Comment by nimuh** [comment]
encode.py contains the functions for simulations. The functions create a single dataframe that contains a type feature which has CASE or CONTROL for each simulated genotype.
