### ISSUE TITLE
Identify and implement  appropriate encoding for the SNP data

### ISSUE THREAD

**Issue by mahdi-b** [mahdi-b/GWASDS#5]
Find 4 papers that use SNPs and deep learning and see what types of encoding they used. 
Can we formulate pros and cons of each encoding approach?
We need to implement each method so that it's seamless to explore them when building the neural network.

**Comment by nimuh** [comment]
encode.py currently only contains a function to perform genotypic encoding.

**Comment by nimuh** [comment]
encode.py and sims.ipynb simulate genotype data for 220000 SNPs. The encodings done are the additive, genotypic, and recessive/dominant models. sims.ipynb contains explanations for each encoding approach and encode.py contains the code for performing the simulations.
